BANNED_WORDS: set[str] = {
    "fuck", "fucker", "fucking", "fucked", "fucks",
    "shit", "shitting", "shitter", "shitted",
    "ass", "asshole", "asses",
    "bitch", "bitches", "bitching",
    "cunt", "cunts",
    "cock", "cocks",
    "dick", "dicks",
    "pussy", "pussies",
    "whore", "whores",
    "slut", "sluts",
    "bastard", "bastards",
    "prick", "pricks",
    "twat", "twats",
    "wank", "wanker", "wankers",
    "piss", "pissed", "pisser",
    "porn", "porno",
    "rape", "raping", "rapist",
    "nigger", "nigga",
    "faggot", "fag",
    "dyke",
    "chink",
    "spic",
    "kike",
    "tranny",
}
